<?php
$this->headTitle("FHEP | Triaje");
$this->head;

$hoy = date("Y-m-d%");

//        echo "<pre>";
//            print_r($hoy);
//            exit;
?>
<!-- DataTable -->
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/tbl_list_pacientes.js') ?>
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/editablegrid-2.1.0-b13.js') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/style.css') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/responsive.css') ?>



<div class="container mt-4">
    <!-- encabezado -->
    <div class="main-header">
        <div class="row">
            <div class="col-lg-7">
                <h2>Pacientes</h2>
                <em>Triaje de Pacientes.</em>
            </div>
            <div class="col-12 mt-4">
                
                    <a href="<?php echo $this->basePath(); ?>/citas/nueva"  class="btn btn-primary"><i class="fa-light fa-calendar-pen"></i> Agregar Nueva</a> 
                    <a href="<?php echo $this->basePath(); ?>/pacientes/exportexceltriaje"  class="btn btn-success"><i class="fa-light fa-file-excel"></i> Exportar Excel</a>
                    <a href="<?php echo $this->basePath(); ?>/pacientes/exportpdftriaje" target="_blank"  class="btn btn-danger"><i class="fa-light fa-file-pdf"></i> Exportar PDF</a>
                    <!--<a href="javascript:imprimirDiv()" class="btn btn-warning"><i class="fal fa-1x fa-print"></i> Imprimir</a>-->
                
            </div>
        </div>
    </div>
    <!-- /encabezado -->
    <div class="border " style="padding: 10px;">
        <div class="">
            <h5 class="">Tabla de Consultas</h5>
        </div><!-- /.box-header -->
        <div class="content">
            <div id="_imprimir" class="hide" >

                <div style="text-align: center;"><h3>FUNDACIÓN HOSPITAL DE EMERGENCIA POLICIAL</h3></div>
                <img src="<?php echo $this->basePath(); ?>/img/logo.png" height="80" style="position: absolute; left: 44px; top: -1px; "  >
                <div style="text-align: center;"><h3>Tabla de Citas</h3></div>
                <style>
                    table {
                        font-family: arial, sans-serif;
                        border-collapse: collapse;
                        width: 100%;
                    }

                    td, th {
                        border: 1px solid #dddddd;
                        text-align: left;
                        padding: 8px;
                    }

                    tr:nth-child(even) {
                        background-color: #dddddd;
                    }
                </style>

                <table>

                    <tbody>

                        <tr>
                            <th>Cód. Afiliado</th>
                            <th>N° Expediente</th>
                            <th>Nombre Completo</th>
                            <th>Especialidad</th>
                            <th>Medico</th>
                            <th>Fecha</th>
                        </tr>
                        <tr>
                            <td><span id="h_codigo_afiliado" style='font-weight: 600;'></span></td>
                            <td>N° Expediente: <span id="h_n_expediente" style='font-weight: 600;'></span></td>
                            <td>Nombre Completo: <span id="h_nombre_afiliado" style='font-weight: 600;'></span></td>
                            <td>Número de Expediente: <span id="h_especialidad" style='font-weight: 600;'></span></td>
                            <td>Medico: <span id="h_nombre_afiliado" style='font-weight: 600;'></span></td>
                            <td>Fecha: <span id="h_nombre_afiliado" style='font-weight: 600;'></span></td>
                        </tr>
                    </tbody>
                </table>
            </div>



            <div class="row">

                <div class="col-sm-5  me-auto ">
                    <div class="form-group" style="padding-top: 30px; ">
                        Mostrando 
                        <select class="form-contr" id="pagesizes" data-parsley-group="block2" name="pagesizes">
                            <option value="10">10</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                            <option value="500">500</option>
                        </select>
                        Resultados por página
                    </div>
                </div>
                <div class="col-lg-3 ms-auto">
                    <div class="input-group flex-nowrap">
                        <label></label>
                        <input type="text" class="form-control" id="filter"  autocomplete="off" placeholder="">
                        <span class="input-group-text" ><i class="bi bi-std bi-search form-control-feedback"></i></span>
                    </div>

                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-12 ">
                    <!-- Grid contents -->
                    <div id="divtabla" style="min-height: 400px; overflow-x: auto;">
                        <center>
                            <div style="margin: 100px;">
                                <span >
                                    <img src="<?php echo $this->basePath(); ?>/img/ajax-loader.gif" width="80" >
                                </span>
                            </div>
                        </center>
                    </div>
                </div>
            </div>
            <!-- Paginator control -->
            <div class="row">
                <div class="col-sm-12">
                    <div id="paginator" class="pull-right"></div>
                </div>
            </div>
        </div>
    </div> 
</div><!-- /.box -->

<!--MODAL PARA LLAMAR DESDE LA TABLA-->
<div class="modal fade" id="mod_camb_estado" tabindex="-1" role="dialog" aria-labelledby="camb_estado" aria-hidden="true">
    <div class="modal-dialog" role="document"> 

        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="camb_estado">Cambiar Estado de Cita</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form id="id_frm_name" method="post" action="<?php echo $this->basePath(); ?>/pacientes/triaje" enctype="multipart/form-data" data-parsley-validate >
                <div class="modal-body">
                    <input type="hidden" id="id_cita" name="id_cita">
                    <!--                    <div class="form-group">
                                            <label for="recipient-name" class="col-form-label">Estado Actual:</label>
                                            <input type="text" class="form-control" name="e_actual" id="e_actual">
                                        </div>-->
                    <div class="form-group">
                        <label for="sangre">Estado  *</label>
                        <select class="form-control" id="nombre_ts"  required  name="id_estado_cita">
                            <option value="">Seleccione un estado *</option>
                            <?php foreach ($this->estado as $d): ?>
                                <option  title="<?php echo $d['nombre_ecm'] ?>" value="<?php echo $d['id'] ?>" ><?php echo $d['nombre_ecm'] ?></option>
                            <?php endforeach; ?>
                        </select>

                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Motivo:</label>
                        <textarea class="form-control" name="mitivo_cambio" id="motivo" rows="3"></textarea>
                    </div>

                    <div class="form-group">
                        <label for="fecha_cita">Fecha y Hora de Cita:</label>
                        <input type="datetime-local" id="fecha_cita" class="form-control" name="fecha_cita">
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Cambiar Estado</button>
                </div> 
            </form>
        </div>
    </div>
</div>


<script>

    function cambiarEstado(id) {
        $('#id_cita').val(id);
        var mod_camb_estado = new bootstrap.Modal(document.getElementById('mod_camb_estado'), {
            keyboard: false
        });

        mod_camb_estado.show();
        //$('#btn_crear_rep_depto').removeClass('disabled');
    }

//            $('#frm_rep_vac_depto').on('submit', function () {
//                $('#btn_crear_rep_depto').addClass('disabled');
//                $('#mod_reporte_vac_depto').modal('hide');
//            });

</script>

<script type="text/javascript">

    direcciones("<?php echo $this->basePath() ?>/pacientes/gettablapacientes", "<?php echo $this->basePath() ?>");
    var datagrid = new DatabaseGrid("tbl_afiliados");//me falta saber de donde la llamare 

    window.onload = function () {

        $("#filter").keyup(function () {

            datagrid.editableGrid.filter($(this).val());
        });
        $("#pagesizes").change(function () {
            datagrid.editableGrid.setPageSize($(this).val());
        });

    };



</script>


<script>
    function imprimirDiv() {
        var p = 'Recibida por: <?php echo $_SESSION['auth']['usuario'] ?> el <?php echo date('d/m/Y'); ?>';
        $("#_pie").html(p);
        $("#_hd1").hide();
        $("#p_especialidad").html($('#id_especialidad option:selected').text());


        //        $("#_hid2").hide();
        //        $("#_hid3").hide();
        //        $("#_hid4").hide();
        //        $("#_hid5").show();
        //        $("#_hid6").hide();
        //        $("#_hid7").show();
        //        $("#_hid8").hide();
        //
        $("#_pie").css("font-size", "20px");
        //        $("#det_1").css("font-size","10px");
        //        $("#det_2").css("font-size","10px");
        //        $("#det_3").css("font-size","10px");

        var objeto = document.getElementById('_imprimir'); //obtenemos el objeto a imprimir
        var ventana = window.open('', '_blank'); //abrimos una ventana vacía nueva
        ventana.document.write(objeto.innerHTML); //imprimimos el HTML del objeto en la nueva ventana
        ventana.document.close(); //cerramos el documento
        ventana.print(); //imprimimos la ventana
        ventana.close(); //cerramos la ventana

        $("#_hd1").show();
        //        $("#_hid2").show();
        //        $("#_hid3").show();
        //        $("#_hid4").show();
        //        $("#_hid5").hide();
        //        $("#_hid6").show();
        //        $("#_hid7").hide();
        //        $("#_hid8").show();
        $("#_pie").html("");
        $("#_pie").css("font-size", "14px");
        //        $("#det_1").css("font-size","14px");
        //        $("#det_2").css("font-size","14px");
        //        $("#det_3").css("font-size","14px");
    }

</script>
<script>
    $("#dni").keyup(function () {//Elemento que voy a observar "#nombreIdElemento"
        var val = $(this).val(); //Asignamos el valor del elemento observado
        $("#nombre_afiliado").val("");
        $("#tipo_afiliado").val("");
        $("#num_afiliado").val("");
        $("#h_nombre_afiliado").val("");
        $("#h_tipo_afiliado").val("");
        $("#h_num_afiliado").val("");


        var listo = false;
        if (val.length >= 13 && val.length <= 15) {
            var regexp;

            regexp = /^[0-9]{4}[-| ]?[0-9]{4}[-| ]?[0-9]{5}$/;

            if (regexp.test(val))
            {
                listo = true;
                $("#respId").html("<div class=\"semibold\"><b>Procesando....</b>   <img src=\"<?php $this->basePath() ?>/img/ajax-loader.gif\" width=\"20\" ></div>");

            } else {
                listo = false;
                $("#respId").html("");

            }
        }
        if (listo) {
            $.ajax({
                type: "POST", //Metodo de envio
                url: "<?php echo $this->url('afiliados/getnombreafiliado') ?>", //URL del jsp que va a procesar mi solicitud asíncrona
                traditional: true,
                dataType: 'json',
                data: {id: val}, //{nombre-de-parametro:Valor-para-el-parametro}
                beforeSend: function () {
                    $("#respuesta_id_afiliado").val("");//Limpiar el campo de respuesta
                },
                success: function (data) {

                    if (data.estado === 'ok') {

                        $("#p_nombre_afiliado").html(data.d.nombres);
                        $("#p_tipo_afiliado").html(data.d.nombre_ta);
                        $("#p_num_afiliado").html(data.d.id_afiliado);
                        $("#h_nombre_afiliado").html(data.d.nombres);
                        $("#h_tipo_afiliado").html(data.d.nombre_ta);
                        $("#h_num_afiliado").html(data.d.id_afiliado);
                        $("#id_afiliado").val(data.d.id_afiliado);





                        $("#btn_enviar").removeClass('disabled');
                    } else {

                        mensajeAutoERROR('Error', data.mensaje);
                        $("#btn_enviar").addClass('disabled');
                    }
                }

            });
        }
    });


</script>

