<?php
$this->headTitle("FHEP | Tipos de Solicitud");
$this->head;
$this->headLink()->prependStylesheet($this->basePath() . '/firma_sello/styles.css');
$this->headScript()->prependFile($this->basePath() . '/firma_sello/validations.js');
$endpoint =  "{$this->basePath()}/mantenimientos/guardar-firma-sello"
?>
<div class="container mt-4">
    <div class="main-header">
        <div class="row">
            <div class="col-lg-7">
                <h2>Mantenimiento</h2>
                <em>Firma y Sello</em>
            </div>
            <div class="col-12 mt-4">
                <a href="javascript:mostraragregartiposoli()"  class="btn btn-primary"><span class="fa fa-eye"></span>  Previsualizar Examen</a>
                <a href="<?php echo $this->basePath(); ?>/mantenimientos/exportarpdftiposoli" target="_blank"  class="btn btn-danger"><i class="fa-light fa-file-pdf"></i> Exportar PDF</a>
            </div>
        </div>
    </div>

    <div class="firma-sello container">
        <h2>Edición</h2>
        <h3>Nombre: <?php echo $user->usuario ?> </h3>

        <form id="firma-sello" action="/public/mantenimientos/guardar-firma-sello" method="post" enctype="multipart/form-data">
            <div class="row files">
                <div class="col firma">
                    <h4 class="title">Firma</h4>
                    <input class="file" type="file" id="firma-file" name="firma" accept="image/png, image/jpeg" />
                    <div class="preview">
                        <img class="photo" id="firma-photo" alt="Imagen de firma" />
                        <i class="close-icon fa-regular fa-circle-xmark"></i>
                    </div>
                </div>
            </div>
            <div class="col sello">
                <h4 class="title">Sello</h4>
                <input class="file" type="file" id="sello-file" name="sello" accept="image/png, image/jpeg" />
                <div class="preview">
                    <img class="photo" id="sello-photo" alt="Imagen de sello" />
                    <i class="close-icon fa-regular fa-circle-xmark"></i>
                </div>
            </div>
            <div class="row submit">
                <div class="col-12">
                    <button type="submit" class="btn-submit btn btn-primary">Guardar firma y sello</button>
                </div>
            </div>
        </form>
        <br />
        <br />
        <pre><?php var_dump($model)  ?></pre>
        <pre><?php var_dump($user)  ?></pre>

    </div>
</div>