<?php
$this->headTitle("FHEP | Tipos de Solicitud");
$this->head;
$this->headLink()->prependStylesheet($this->basePath() . '/firma_sello/styles.css');
$this->headScript()->prependFile($this->basePath() . '/firma_sello/validations.js');
$endpoint =  "{$this->basePath()}/mantenimientos/guardar-firma-sello"
?>
<div class="container mt-4">
    <div class="main-header">
        <div class="row">
            <div class="col-lg-7">
                <h2>Mantenimiento</h2>
                <em>Firmas y Sellos</em>
            </div>

        </div>
    </div>

    <div class="firma-sello container">
        <h2>Edición de Firmas</h2>
        <h4>Nombre: <?php echo $user->usuario ?> </h4>
        <a href="<?php echo $this->basePath(); ?>/mantenimientos/firmasello" class="btn btn-warning" ><span class="fa fa-undo"></span> Regresar</a>
        <br />
        <br />
        <br />
        <br />

        <form id="firma-sello" action="<?php echo $this->basePath(); ?>/mantenimientos/editar-firma-sello/<?php echo $model->id ?>" method="post" enctype="multipart/form-data">
            <div class="row files">
                <div class="col firma">
                    <h4 class="title">Firma</h4>
                    <input class="file" type="file" id="firma-file" name="firma" accept="image/png, image/jpeg" />
                    <div class="preview">
                        <img class="photo" id="firma-photo" alt="Imagen de firma" />
                        <i class="close-icon fa-regular fa-circle-xmark"></i>
                    </div>
                </div>
            </div>
            <div class="col sello">
                <h4 class="title">Sello</h4>
                <input class="file" type="file" id="sello-file" name="sello" accept="image/png, image/jpeg" />
                <div class="preview">
                    <img class="photo" id="sello-photo" alt="Imagen de sello" />
                    <i class="close-icon fa-regular fa-circle-xmark"></i>
                </div>
            </div>
            <div class="row submit">
                <div class="col-12">
                    <button type="submit" class="btn-submit btn btn-primary">Guardar firma y sello</button>
                </div>
            </div>
        </form>
        <br />
        <br />
        <div class="row">
            <div class="col-md-6">
                <img width="300" src="<?php echo "/public" .$model->Firma ?>" class="img-fluid img-thumbnail" alt="<?php echo "/public" . $model->Firma ?>" />
            </div>
            <div class="col-md-6">
                <img width="300" src="<?php echo "/public" .$model->Sello ?>" class="img-fluid img-thumbnail" alt="<?php echo "/public" . $model->Sello ?>" />
            </div>
        </div>

    </div>
</div>