<?php
$this->headTitle("FHEP | Consultas");
$this->head;
?>
<!-- DataTable -->
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/tbl_list_general_citas.js') ?>
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/editablegrid-2.1.0-b13.js') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/style.css') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/responsive.css') ?>

<div class="container mt-4">
    <!-- encabezado -->
    <div class="main-header">
        <div class="row">
            <div class="col-lg-7">
                <h2>Citas </h2>
                <em>General de Citas.</em>
            </div>

            <div class="col-12 mt-5">
                <a href="<?php echo $this->basePath(); ?>/citas/nueva"  class="btn btn-primary btn-primary"><i class="fa-light fa-plus"></i> Agregar Nueva</a>   
<!--                <a href="<?php echo $this->basePath(); ?>/pacientes/exportexceltriaje"  class="btn btn-success"><i class="fa-light fa-file-excel"></i> Exportar Excel</a>
                <a href="<?php echo $this->basePath(); ?>/citas/exportarpdfgenerlcitas" target="_blank"  class="btn btn-danger"><i class="fa-light fa-file-pdf"></i> Exportar PDF</a>-->
            </div>
        </div>
    </div>
    <!-- /encabezado -->
    <div class="border " style="padding: 10px;">
        <div class="">
            <h5 class="">Tabla de Consultas</h5>
        </div><!-- /.box-header -->
        <div class="content">
            <div class="row">
                <div class="col-sm-5  me-auto ">
                    <div class="form-group" style="padding-top: 30px; ">
                        Mostrando 
                        <select class="form-contr" id="pagesizes" data-parsley-group="block2" name="pagesizes">
                            <option value="10">10</option>
                            <option value="25">25</option>
                            <option value="50">50</option>
                            <option value="100">100</option>
                            <option value="500">500</option>
                        </select>
                        Resultados por página
                    </div>
                </div>
                <div class="col-lg-3 ms-auto">
                    <div class="input-group flex-nowrap">
                        <label></label>
                        <input type="text" class="form-control" id="filter"  autocomplete="off" placeholder="">
                        <span class="input-group-text" ><i class="bi bi-std bi-search form-control-feedback"></i></span>
                    </div>

                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-sm-12 ">
                    <!-- Grid contents -->
                    <div id="divtabla" style="min-height: 400px; overflow-x: auto;">
                        <center>
                            <div style="margin: 100px;">
                                <span >
                                    <img src="<?php echo $this->basePath(); ?>/img/ajax-loader.gif" width="80" >
                                </span>
                            </div>
                        </center>
                    </div>
                </div>
            </div>
            <!-- Paginator control -->
            <div class="row">
                <div class="col-sm-12">
                    <div id="paginator" class="pull-right"></div>
                </div>
            </div>
        </div>
    </div> 
</div><!-- /.box -->
<?php if (isset($_SESSION['permisos']['Citas']) && $_SESSION['permisos']['Citas']['permiso_actualizacion'] == '1'): ?>

    <!--MODAL PARA LLAMAR DESDE LA TABLA-->
    <div class="modal fade" id="mod_camb_estado" tabindex="-1" role="dialog" aria-labelledby="camb_estado" aria-hidden="true">
        <div class="modal-dialog" role="document"> 

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="camb_estado">Cambiar Estado de Cita</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="id_frm_name" method="post" action="<?php echo $this->basePath(); ?>/citas/gestionarcitas" enctype="multipart/form-data" data-parsley-validate >
                    <div class="modal-body">
                        <input type="hidden" id="id_cita" name="id_cita">
                        <!--                    <div class="form-group">
                                                <label for="recipient-name" class="col-form-label">Estado Actual:</label>
                                                <input type="text" class="form-control" name="e_actual" id="e_actual">
                                            </div>-->
                        <div class="form-group">
                            <label for="sangre">Estado  *</label>
                            <select class="form-control" id="nombre_ts"  required  name="id_estado_cita">
                                <option value="">Seleccione un estado *</option>
                                <?php foreach ($this->estado as $d): ?>
                                    <option  title="<?php echo $d['nombre_ecm'] ?>" value="<?php echo $d['id'] ?>" ><?php echo $d['nombre_ecm'] ?></option>
                                <?php endforeach; ?>
                            </select>

                        </div>

                        <div class="form-group">
                            <label for="recipient-name" class="col-form-label">Motivo:</label>
                            <textarea class="form-control" name="motivo_cambio" id="motivo" rows="3"></textarea>
                        </div>

                        <div class="form-group">
                            <label for="fecha_cita">Fecha y Hora de Cita:</label>
                            <input type="datetime-local" id="fecha_cita" class="form-control" name="fecha_cita">
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Cambiar Estado</button>
                    </div> 
                </form>
            </div>
        </div>
    </div>

<?php endif; ?>
    
    
     <!--MODAL PARA CAMBIAR MEDICO-->
    <div class="modal fade" id="mod_camb_medico" tabindex="-1" role="dialog" aria-labelledby="camb_estado" aria-hidden="true">
        <div class="modal-dialog" role="document"> 

            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="camb_estado">Cambiar Medico General</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form id="id_frm_name" method="post" action="<?php echo $this->basePath(); ?>/citas/cambiarmedico" enctype="multipart/form-data" data-parsley-validate >
                    <div class="modal-body">
                        <input type="hidden" id="id_citam" name="id_cita">
                        <!--                    <div class="form-group">
                                                <label for="recipient-name" class="col-form-label">Estado Actual:</label>
                                                <input type="text" class="form-control" name="e_actual" id="e_actual">
                                            </div>-->
                        <div class="form-group">
                            <label for="sangre">Medicos </label>
                            <select class="form-control" id="nombre_ts"  required  name="id_medico">
                                <option value="">Seleccione Un Medico General </option>
                                <?php foreach ($this->medicos as $d): ?>
                                    <option  title="<?php echo $d['nombre_completo'] ?>" value="<?php echo $d['id'] ?>" ><?php echo $d['nombre_completo'] ?></option>
                                <?php endforeach; ?>
                            </select>

                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Cambiar Estado</button>
                    </div> 
                </form>
            </div>
        </div>
    </div>

<script>

    function cambiarEstado(id) {
        $('#id_cita').val(id);
        var mod_camb_estado = new bootstrap.Modal(document.getElementById('mod_camb_estado'), {
            keyboard: false
        });

        mod_camb_estado.show();
        //$('#btn_crear_rep_depto').removeClass('disabled');
    }

//            $('#frm_rep_vac_depto').on('submit', function () {
//                $('#btn_crear_rep_depto').addClass('disabled');
//                $('#mod_reporte_vac_depto').modal('hide');
//            });

</script>

<script>

    function cambiarMedico(id) {
        $('#id_citam').val(id);
        var mod_camb_medico = new bootstrap.Modal(document.getElementById('mod_camb_medico'), {
            keyboard: false
        });

        mod_camb_medico.show();
        //$('#btn_crear_rep_depto').removeClass('disabled');
    }

//            $('#frm_rep_vac_depto').on('submit', function () {
//                $('#btn_crear_rep_depto').addClass('disabled');
//                $('#mod_reporte_vac_depto').modal('hide');
//            });

</script>

<script type="text/javascript">
    direcciones("<?php echo $this->basePath() ?>/citas/gettblgeneralcitas", "<?php echo $this->basePath() ?>");
    var datagrid = new DatabaseGrid("tbl_cit_medicas");//me falta saber de donde la llamare 

    window.onload = function () {
        $("#filter").keyup(function () {
            datagrid.editableGrid.filter($(this).val());
        });
        $("#pagesizes").change(function () {
            datagrid.editableGrid.setPageSize($(this).val());
        });
    };


</script>