<?php
$this->headTitle("APP | Title");
$this->head;
?>
<!-- DataTable -->
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/tbl_conf_usuarios.js') ?>
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/editablegrid-2.1.0-b13.js') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/style.css') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/responsive.css') ?>


<!-- encabezado -->
<div class="container mt-4">
    <div class="main-header">
        <div class="row">
            <div class="col-lg-6">
                <h2>Objetos</h2>
                <em>Crear Objetos.</em>
            </div>
            <div class="col-lg-6">
                <div class="btn-group pull-right">
                    <a href="<?php echo $this->basePath(); ?>/roles" class="w-75 btn btn-md btn-primary next"><span class="icon icon-std icon-back"></span><i class="fa-thin fa-circle-chevron-left"></i>  Regresar</a>
                </div>
            </div>
        </div>
    </div>


    <!-- /encabezado -->
    <div class="border " style="padding: 10px; min-height: 700px;">
        <div class="row">
            <h3 class="">Agregar Objetos</h3>
        </div><!-- /.box-header -->

        <div class="content">
            <form id="id_frm_name" method="post" action="<?php echo $this->basePath(); ?>/objetos/nuevo" enctype="multipart/form-data" data-parsley-validate >
                <div class="row">
                    <div class="col-md-6">
                        <label>Objeto:</label>
                        <input type="text" class="form-control" name="objeto" id="objeto" maxlength="30" placeholder="Nombre del Objeto" required>
                    </div>
                    <div class="col-md-6 ">
                        <label for="tipo_rol">Tipo de Objeto *</label>
                        <select class="form-control" id="objeto"   name="tipo_objeto">
                            <option value="Adminitravito">Administrativo</option>
                            <option value="Mantenimineto">Mantenimieto</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Descripcion:</label>
                        <input type="text" class="form-control" name="descripcion" id="descripcion" maxlength="100" placeholder="Descripcion"" required>
                    </div>
                    <div class="col-md-6 ">
                        <label for="estado">Estado de Objeto *</label>
                        <select class="form-control" id="objeto_estado" name="estado">
                            <option value="">Estado de Objeto *</option>
                            <option value="Activo">Activo</option>
                            <option value="Inactivo">Inactivo</option>
                        </select>
                    </div>
                </div>



                 <div class="row mt-4">
                    <h3 class="">Confirmar y Guardar</h3>
                </div>
                <div class="col mt-2">
                  <div class="d-grid gap-2 col-4">
                    <button class=" btn btn-primary" type="submit" id="btnGuardar"><i class="fa fa-save"></i> Terminar y Guardar</button>
                    <!--<button class="btn btn-danger" onclick="cancelarform()"  type="button"><i class="fa fa-arrow-circle-left"></i> Cancelar</button>-->
                </div>
                     </div>
            </form>
        </div>
    </div>
</div>










<script type="text/javascript">


</script>