<?php
$this->headTitle("FHEP | Agregar Roles");
$this->head;
$info = $this->info;

if (isset($_SESSION["auth"])) {

    $nombre_usuario = $_SESSION["auth"]['usuario'];

    $DateAndTime = date('Y-m-d h:i:s a', time());
}
?>
<!-- DataTable -->
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/tbl_conf_usuarios.js') ?>
<?php $this->headScript()->prependFile($this->basePath() . '/tablaEditable/js/editablegrid-2.1.0-b13.js') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/style.css') ?>
<?php $this->headLink()->prependStylesheet($this->basePath() . '/tablaEditable/css/responsive.css') ?>


<!-- encabezado -->
<div class="container mt-4">
    <div class="main-header">
        <div class="row">
            <div class="col-lg-6">
                <h2>Correo</h2>
                <em>Editar Correo.</em>
            </div>
            <div class="col-lg-6">
                <div class="btn-group pull-right">
                    <a href="<?php echo $this->basePath(); ?>/" class="w-75 btn btn-md btn-primary next"><span class="icon icon-std icon-back"></span><i class="fa-thin fa-circle-chevron-left"></i>  Regresar</a>
                </div>
            </div>
        </div>
    </div>


    <!-- /encabezado -->
    <div class="border " style="padding: 10px; min-height: 700px;">
        <div class="row">
            <h3 class="">Información Del Correo</h3>
        </div><!-- /.box-header -->

        <div class="content">
            <form id="id_frm_name" method="post" action="<?php echo $this->basePath(); ?>/correos" enctype="multipart/form-data" data-parsley-validate >


                <input type="hidden" id="id_cita" name="id" value="1"  >
                  <input type="hidden" id="fecha" name="fecha" value="<?php echo $DateAndTime ?>"  >

                <div class="row">
                    <div class="col-md-6">
                        <label>Correo de salida :</label>
                        <input type="email" class="form-control" name="correo" id="correo" 
                               maxlength="30" placeholder="Correo" value="<?php echo $info['correo'] ?>" required>
                    </div>

                    <div class="col-md-6">
                        <label>Contraseña:</label>
                        <input type="password" class="form-control" name="contrasena" id="contrasena" 
                               maxlength="100"  value="<?php echo $info['contrasena'] ?>"  
                               placeholder="Descripcion"" required>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Nombre para mostrar:</label>
                        <input type="text" class="form-control" name="nombre" id="nombre" maxlength="100" 
                               placeholder="Descripcion" value="<?php echo $info['nombre'] ?>" required>
                    </div>
                    <div class="col-md-6">
                        <label>Servidor SMTP de Salida:</label>
                        <input type="text" class="form-control" name="servidor" id="servidor" maxlength="100" 
                               value="<?php echo $info['servidor'] ?>" placeholder="Descripcion"" required>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <label> Puerto SMTP de Salida:</label>
                        <input type="text" class="form-control" name="puerto" id="puerto" maxlength="100" 
                               value="<?php echo $info['puerto'] ?>" placeholder="Descripcion"" required>
                    </div>
                </div>
                <div class="row mt-4">
                    <h3 class="">Confirmar y Guardar</h3>
                </div>
                <div class="col mt-2">
                    <div class="d-grid gap-2 col-4">
                        <button class=" btn btn-primary" type="submit" id="btnGuardar"><i class="fa fa-save"></i>Terminar y Guardar</button>
                        <!--<button class="btn btn-danger" onclick="cancelarform()"  type="button"><i class="fa fa-arrow-circle-left"></i> Cancelar</button>-->
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>



<script type="text/javascript">


</script>