<?php
$tl = "Bienvenido";
if (!isset($_SESSION["auth"])) {
    $tl = "LogIn";
} 
$this->headTitle($tl);
$this->head;
?>
<?php
if (!isset($_SESSION["auth"])):
    $max_len_pass = $this->max;
    $min_len_pass = $this->min;
    ?>




    <!--====================================================================================================================================-->

    <div class="container-fluid mt-4">		
        <div class="row">
            <div class="col-md-5 ">
                <div class="row mt-4">
                    <div class="col-md-12 my-auto">
                        <img src="<?php echo $this->basePath(); ?>/img/logo.png" width="550" height="550" class ="img-fluid logo" alt="inicio" >
                    </div>
                </div>
            </div>
    <!--                <div class="col"><img src="img\logo.png" width="450" height="450" class="img-fluid "></div>-->
            <div class="col">
                <form id="frm_login" method="post" enctype="multipart/form-data" action="<?php echo $this->basePath(); ?>/usuarios/login" data-parsley-validate >
                    <br> <br> <br>
                    <h3 align="center">INICIO DE SESIÓN</h3> <br>	
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <i class="fad fa-users"></i>
                                <label class="form-label" for="typeEmailX">Usuario</label>
                                <input type="text" id="usuario" class="form-control form-control-lg" name="usuario"   
                                       required onkeypress="return soloLetras(event)" onkeyup="aaa(this, event)" 
                                       data-parsley-range="[5,20]"
                                       style="text-transform:uppercase;" onkeyup="javascript:this.value = this.value.toUpperCase();" />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col">
                                <i class="fad fa-key"></i>
                                <label class="form-label" for="typeEmailX">Contraseña</label>
                                <div class="input-group flex-nowrap">
                                    <input type="password"  name="contrasenia" class="form-control form-control-lg" id="pass"  autocomplete="off"
                                           data-parsley-range="[<?php echo $min_len_pass; ?>,<?php echo $max_len_pass; ?>]" 
                                           data-parsley-errors-container="#err_pass"
                                           required="">
                                    <span class="input-group-text" onclick="mostrarContrasena('pass')"><i id="icon_pass" class="fad fa-eye"></i></span>
                                </div>
                                <div id="err_pass"></div>
                            </div>
                        </div>
                    </div>

                    <br>
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <div class="d-grid gap-2">
                                    <button class="btn btn-success btn-lg">
                                        <i class="fa-light fa-right-to-bracket"></i>
                                        INICIAR
                                    </button>
                                </div>
                            </div>
                        </div>     
                        <div class="row mt-2">
                            <div class="col d-grid gap-2">
                                <a class="btn btn-primary btn-lg " 
                                   href="<?php echo $this->basePath() ?>/usuarios/autoregistro" role="button">Registrarse <i class="fa-light fa-upload"></i> </a>
                            </div>
                        </div>

                        <div class="form-outline form-primary  mt-2 mb-0">
                            <p class="small mb-5 pb-lg-2">
                                <a class="text-primary-50" href="<?php echo $this->basePath() ?>/usuarios/recupass"
                                   >¿Olvidó su usuario o contraseña?</a
                                >
                            </p>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
<?php else: ?>



    <br>
    <div class="container mt-5">
        <!--<div class="box-header">-->

        <div class="box-title">
            <div class="row">
                <div class="col-lg-12">
                    <h2>BIENVENIDO A FHEP</h2>
                </div>
            </div>
        </div>





        <div class="col-lg-3 col-xs-6 container-fluid">
            <!-- small box -->
            <div class="small-box bg-green">
                <div class="inner">

                    <h3>
    <?php echo $this->num_medi['num_medicos'] ?>
                    </h3>
                    <p> Medicos<small>Total De Medicos Activos</small></p>
                </div>
                <div class="icon">
                    <i class="far fa-5x fa-solid fa-user-doctor"></i>
                </div>
                <a href="<?php echo $this->basePath() ?>/afiliados/listmedicos" class="small-box-footer">Mas Info<i class="fal  fa-arrow-circle-right"></i></a>
            </div>
        </div>

                                                                                                                                <!--<img src="<?php echo $this->basePath() ?>/img/inicio.jpeg" width="65%" alt="...">-->
        <div class="col-lg-3 col-xs-6 container-fluid">
            <!-- small box -->
            <div class="small-box bg-blue">
                <div class="inner">

                    <h3>
    <?php echo $this->num_afi['num_afiliados'] ?>
                    </h3>
                    <p> Afiliados<small>Total De Afiliados Activos</small></p>
                </div>
                <div class="icon">
                    <i class="far fa-5x fa-solid fa-user-police-tie"></i>
                </div>
                <a href="<?php echo $this->url("afiliados") ?>" class="small-box-footer">Mas Info<i class="fal  fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-xs-6 container-fluid">
            <!-- small box -->
            <div class="small-box bg-orange">
                <div class="inner">

                    <h3>
    <?php echo $this->num_citas['num_citas'] ?>
                    </h3>
                    <p> Citas<small>Total De Citas Para Hoy</small></p>
                </div>
                <div class="icon">
                    <i class="far fa-5x fa-solid fa-calendar-days"></i>
                </div>
                <a href="<?php echo $this->basePath() ?>/citas/gestionarcitas" class="small-box-footer">Mas Info<i class="fal  fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-xs-6 container-fluid">
            <!-- small box -->
            <div class="small-box bg-red">
                <div class="inner">

                    <h3>
    <?php echo $this->num_bene['num_beneficiarios'] ?>
                    </h3>
                    <p> Beneficiarios<small>Total De Beneficiarios</small></p>
                </div>
                <div class="icon">
                    <i class="far fa-5x fa-solid fa-users"></i>
                </div>
                <a href="<?php echo $this->url("home") ?>" class="small-box-footer">Mas Info<i class="fal  fa-arrow-circle-right"></i></a>
            </div>
        </div>
    </div>

            <!--<img src="<?php echo $this->basePath(); ?>/img/inicio.jpeg" >-->


<?php endif; ?>
<!--prueba loca-->


<!-- The slideshow -->

<script>
    function mostrarContrasena(id) {
        var tipo = document.getElementById(id);
        if (tipo.type == "password") {
            tipo.type = "text";
            $('#icon_pass').removeClass('fa-eye');
            $('#icon_pass').addClass('fa-eye-slash');

        } else {
            tipo.type = "password";
            $('#icon_pass').removeClass('fa-eye-slash');
            $('#icon_pass').addClass('fa-eye');
        }
    }
</script>
<script>
    window.onload = function () {
        var myInput = document.getElementById('Contraseña');
        myInput.onpaste = function (e) {
            e.preventDefault();
        }
        myInput.oncopy = function (e) {
            e.preventDefault();
        }


        var myInput1 = document.getElementById('usuario');
        myInput1.onpaste = function (e) {
            e.preventDefault();
        }
        myInput1.oncopy = function (e) {
            e.preventDefault();
        }
    }
</script>
<script language="javascript">
    function aaa(campo, event) {
        CadenaaReemplazar = " ";
        CadenaReemplazo = "";
        CadenaTexto = campo.value;
        CadenaTextoNueva = CadenaTexto.split(CadenaaReemplazar).join(CadenaReemplazo);
        campo.value = CadenaTextoNueva;
    }
</script>
<script>
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
        especiales = "8-37-39-46";
        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }
        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }
</script>

<script>
    function soloLetras(e) {
        key = e.keyCode || e.which;
        tecla = String.fromCharCode(key).toLowerCase();
        letras = " áéíóúabcdefghijklmnñopqrstuvwxyz0123456789Ñ";
        especiales = "8-37-39-46";
        tecla_especial = false
        for (var i in especiales) {
            if (key == especiales[i]) {
                tecla_especial = true;
                break;
            }
        }
        if (letras.indexOf(tecla) == -1 && !tecla_especial) {
            return false;
        }
    }
</script>